services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "1000"
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - ./data:/var/lib/grafana
    networks:
      red:
        ipv4_address: 10.10.1.7

networks:
  red:
    external: true
