services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:32.0.2
    container_name: nextcloud
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      MYSQL_HOST: 10.10.1.3
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8081:80"
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      red:
        ipv4_address: 10.10.1.20

networks:
  red:
    external: true
