services:
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    user: "node-red"
    env_file: .env
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
    networks:
      red:
        ipv4_address: 10.10.1.5
    dns:
      - 10.10.1.30
      - 1.1.1.1

networks:
  red:
    external: true
