services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SERVERURL: ${SERVERURL}
      SERVERPORT: ${SERVERPORT}
      PEERS: ${PEERS}
      PEERDNS: ${PEERDNS}
      INTERNAL_SUBNET: ${INTERNAL_SUBNET}
      ALLOWEDIPS: ${ALLOWEDIPS}
      LOG_CONFS: ${LOG_CONFS}
    ports:
      - "51821:51820/udp"
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      red:
        ipv4_address: 10.10.1.2

networks:
  red:
    external: true
